### ISSUE TITLE
Add preferences for alarm threshold - balance and expiry

### ISSUE THREAD

**Issue by ccjr** [ccjr/ptel#11]

**Comment by waisblut** [comment]
Does ptel, allow NEGATIVE credit?

**Comment by ccjr** [comment]
I am not sure, but we could add a check for `balance <= 0` to kind of support that use case.

**Comment by waisblut** [comment]
Tem uma coisa que preciso arrumar....
Ao utilizar o AlertDialog, caso o usuário saia do App (HOME BUTTON)...ele acusa:

Activity mobi.ccjr.ptel.activity.PrefsActivity has leaked window
